spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: contateste.dev1@gmail.com
    password: doeqfghzwcuedwed
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
api:
  jwt:
    secret: ed2befb11499489e2570cb053f774b8ed93e89eddab3f78867a2a5f32c58845e
